In [1]:
import pandas as pd
import numpy as np 

C:\Users\raghav.aggarwal\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [3]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df["Category"].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
def get_spam_number(x):
    if x=="spam":
        return 1
    return 0

In [8]:
df['spam']=df["Category"].apply(get_spam_number)
# lambda x: 1 if x=='spam' else 0

In [9]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df["Message"],df["spam"],test_size=0.2)

In [12]:
x_train.shape

(4457,)

In [13]:
x_test.shape

(1115,)

In [14]:
type(x_test)

pandas.core.series.Series

In [15]:
type(y_train)

pandas.core.series.Series

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
v=CountVectorizer()

In [21]:
x_train_cv=v.fit_transform(x_train.values)#because the want the input in form of numpy and not in formn of pandas 
x_train_cv

<4457x7694 sparse matrix of type '<class 'numpy.int64'>'
	with 59451 stored elements in Compressed Sparse Row format>

In [22]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [24]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [25]:
v.vocabulary_

{'met': 4426,
 'you': 7660,
 'as': 1065,
 'stranger': 6464,
 'and': 946,
 'choose': 1771,
 'my': 4625,
 'friend': 2971,
 'long': 4158,
 'the': 6763,
 'world': 7550,
 'stands': 6393,
 'our': 4963,
 'friendship': 2974,
 'never': 4708,
 'ends': 2565,
 'lets': 4057,
 'be': 1246,
 'friends': 2972,
 'forever': 2911,
 'gud': 3237,
 'nitz': 4745,
 'ok': 4872,
 'then': 6774,
 'yes': 7644,
 'they': 6786,
 'replied': 5678,
 'mail': 4283,
 'going': 3150,
 'to': 6883,
 'management': 4304,
 'office': 4858,
 'later': 4001,
 'plus': 5221,
 'will': 7472,
 'in': 3611,
 'bank': 1190,
 'also': 911,
 'or': 4931,
 'on': 4889,
 'wednesday': 7388,
 'everybody': 2648,
 'had': 3266,
 'fun': 3011,
 'this': 6802,
 'evening': 2640,
 'miss': 4473,
 'actually': 794,
 'nvm': 4821,
 'got': 3178,
 'hella': 3368,
 'cash': 1646,
 'we': 7370,
 'still': 6434,
 'for': 2908,
 'lt': 4213,
 'gt': 3233,
 'ish': 3726,
 'shit': 6059,
 'that': 6759,
 'is': 3723,
 'really': 5572,
 'shocking': 6067,
 'scary': 5892,
 'cant': 1611,
 '

In [27]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
np.where(x_train_np[0]!=0)

(array([ 946, 1065, 1246, 1771, 2565, 2911, 2971, 2972, 2974, 3237, 4057,
        4158, 4426, 4625, 4708, 4745, 4963, 6393, 6464, 6763, 7550, 7660],
       dtype=int64),)

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
model=MultinomialNB()

In [32]:
model.fit(x_train_cv,y_train)

MultinomialNB()

In [34]:
x_test_cv=v.transform(x_test)

In [36]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)

In [38]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       964
           1       0.95      0.93      0.94       151

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115

